package com.video.newqu.bean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.video.newqu.bean.MessageListInfo;
import com.video.newqu.bean.UploadVideoInfo;
import com.video.newqu.bean.UserPlayerVideoHistoryList;
import com.video.newqu.bean.WeiChactVideoInfo;
import com.video.newqu.bean.WeiXinVideo;

import com.video.newqu.bean.MessageListInfoDao;
import com.video.newqu.bean.UploadVideoInfoDao;
import com.video.newqu.bean.UserPlayerVideoHistoryListDao;
import com.video.newqu.bean.WeiChactVideoInfoDao;
import com.video.newqu.bean.WeiXinVideoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig messageListInfoDaoConfig;
    private final DaoConfig uploadVideoInfoDaoConfig;
    private final DaoConfig userPlayerVideoHistoryListDaoConfig;
    private final DaoConfig weiChactVideoInfoDaoConfig;
    private final DaoConfig weiXinVideoDaoConfig;

    private final MessageListInfoDao messageListInfoDao;
    private final UploadVideoInfoDao uploadVideoInfoDao;
    private final UserPlayerVideoHistoryListDao userPlayerVideoHistoryListDao;
    private final WeiChactVideoInfoDao weiChactVideoInfoDao;
    private final WeiXinVideoDao weiXinVideoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        messageListInfoDaoConfig = daoConfigMap.get(MessageListInfoDao.class).clone();
        messageListInfoDaoConfig.initIdentityScope(type);

        uploadVideoInfoDaoConfig = daoConfigMap.get(UploadVideoInfoDao.class).clone();
        uploadVideoInfoDaoConfig.initIdentityScope(type);

        userPlayerVideoHistoryListDaoConfig = daoConfigMap.get(UserPlayerVideoHistoryListDao.class).clone();
        userPlayerVideoHistoryListDaoConfig.initIdentityScope(type);

        weiChactVideoInfoDaoConfig = daoConfigMap.get(WeiChactVideoInfoDao.class).clone();
        weiChactVideoInfoDaoConfig.initIdentityScope(type);

        weiXinVideoDaoConfig = daoConfigMap.get(WeiXinVideoDao.class).clone();
        weiXinVideoDaoConfig.initIdentityScope(type);

        messageListInfoDao = new MessageListInfoDao(messageListInfoDaoConfig, this);
        uploadVideoInfoDao = new UploadVideoInfoDao(uploadVideoInfoDaoConfig, this);
        userPlayerVideoHistoryListDao = new UserPlayerVideoHistoryListDao(userPlayerVideoHistoryListDaoConfig, this);
        weiChactVideoInfoDao = new WeiChactVideoInfoDao(weiChactVideoInfoDaoConfig, this);
        weiXinVideoDao = new WeiXinVideoDao(weiXinVideoDaoConfig, this);

        registerDao(MessageListInfo.class, messageListInfoDao);
        registerDao(UploadVideoInfo.class, uploadVideoInfoDao);
        registerDao(UserPlayerVideoHistoryList.class, userPlayerVideoHistoryListDao);
        registerDao(WeiChactVideoInfo.class, weiChactVideoInfoDao);
        registerDao(WeiXinVideo.class, weiXinVideoDao);
    }
    
    public void clear() {
        messageListInfoDaoConfig.clearIdentityScope();
        uploadVideoInfoDaoConfig.clearIdentityScope();
        userPlayerVideoHistoryListDaoConfig.clearIdentityScope();
        weiChactVideoInfoDaoConfig.clearIdentityScope();
        weiXinVideoDaoConfig.clearIdentityScope();
    }

    public MessageListInfoDao getMessageListInfoDao() {
        return messageListInfoDao;
    }

    public UploadVideoInfoDao getUploadVideoInfoDao() {
        return uploadVideoInfoDao;
    }

    public UserPlayerVideoHistoryListDao getUserPlayerVideoHistoryListDao() {
        return userPlayerVideoHistoryListDao;
    }

    public WeiChactVideoInfoDao getWeiChactVideoInfoDao() {
        return weiChactVideoInfoDao;
    }

    public WeiXinVideoDao getWeiXinVideoDao() {
        return weiXinVideoDao;
    }

}
